// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrayScanStandard.Data;

#nullable disable

namespace TrayScanStandard.Migrations
{
    [DbContext(typeof(LinxContext))]
    [Migration("20250412090045_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LinxUniverse.Auth.LinxRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LinxRoles");
                });

            modelBuilder.Entity("LinxUniverse.Auth.LinxUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LinxUsers");
                });

            modelBuilder.Entity("LinxUniverse.Auth.LinxUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("LinxUserRoles");
                });

            modelBuilder.Entity("TrayScanStandard.Data.Models.OKNGCnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("NG1Cnt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NG2Cnt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OKCnt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OKNGCnts");
                });

            modelBuilder.Entity("TrayScanStandard.Data.Models.PalletLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PalletCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PalletType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ZuPanTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PalletLogs");
                });

            modelBuilder.Entity("TrayScanStandard.Data.Models.WarningLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WarningTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WarningLogs");
                });

            modelBuilder.Entity("TrayScanStandard.Data.Models.WcsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WcsLogs");
                });

            modelBuilder.Entity("TrayScanStandard.Data.Models.PalletLog", b =>
                {
                    b.OwnsMany("TrayScanStandard.Data.Models.BatteryInfo", "BatteryInfo", b1 =>
                        {
                            b1.Property<int>("PalletLogId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BatteryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("BatteryLevel")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PalletLogId", "__synthesizedOrdinal");

                            b1.ToTable("PalletLogs");

                            b1.ToJson("BatteryInfo");

                            b1.WithOwner()
                                .HasForeignKey("PalletLogId");
                        });

                    b.Navigation("BatteryInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
